"""
Unified file download router.

Provides GET /files/{file_id}/download for any tool-generated file.
First checks the in-memory file_store, then falls back to downloading
directly from Claude's Files API (for files generated by skills/code execution).
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import Response, JSONResponse, StreamingResponse
import logging

from core.file_store import get_file, list_files

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/files", tags=["files"])

# MIME type mapping
_MIME_TYPES = {
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "pdf":  "application/pdf",
    "csv":  "text/csv",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "json": "application/json",
    "txt":  "text/plain",
    "md":   "text/markdown",
    "png":  "image/png",
    "jpg":  "image/jpeg",
    "jpeg": "image/jpeg",
}


def _get_mime(filename: str, file_type: str = "") -> str:
    """Get MIME type from file_type or filename extension."""
    if file_type and file_type in _MIME_TYPES:
        return _MIME_TYPES[file_type]
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    return _MIME_TYPES.get(ext, "application/octet-stream")


@router.get("/{file_id}/download")
async def download_file(file_id: str, filename: str = None, request: Request = None):
    """
    Download a generated file by its ID.
    
    1. First checks in-memory file_store (for files stored during current container lifetime)
    2. Falls back to Claude's Files API (for skill/code execution generated files)
    """
    # Try in-memory store first
    entry = get_file(file_id)
    if entry is not None:
        mime = _get_mime(entry.filename, entry.file_type)
        dl_filename = filename or entry.filename
        return Response(
            content=entry.data,
            media_type=mime,
            headers={
                "Content-Disposition": f'attachment; filename="{dl_filename}"',
                "Content-Length": str(len(entry.data)),
            },
        )

    # Fallback: try Claude's Files API directly
    # This handles the case where the in-memory store was lost (container restart)
    # but the file still exists in Claude's Files API
    if file_id.startswith("file_"):
        try:
            import anthropic
            import os

            # Get the API key — try from request auth header first, then env
            api_key = None
            if request:
                auth_header = request.headers.get("authorization", "")
                if auth_header.startswith("Bearer "):
                    api_key = auth_header[7:]
            if not api_key:
                api_key = os.getenv("ANTHROPIC_API_KEY")
            if not api_key:
                # Try to get from config
                try:
                    from config import settings
                    api_key = getattr(settings, "ANTHROPIC_API_KEY", None)
                except Exception:
                    pass

            if api_key:
                client = anthropic.Anthropic(api_key=api_key)
                files_beta = ["files-api-2025-04-14"]

                # Get file metadata first
                try:
                    metadata = client.beta.files.retrieve_metadata(
                        file_id,
                        betas=files_beta,
                    )
                    dl_filename = filename or getattr(metadata, "filename", None) or f"download_{file_id}"
                    mime = _get_mime(dl_filename)

                    # Download the file content
                    file_content = client.beta.files.download(
                        file_id,
                        betas=files_beta,
                    )
                    # SDK may return BinaryResponseContent with iter_bytes() or read()
                    if isinstance(file_content, bytes):
                        data = file_content
                    elif hasattr(file_content, "iter_bytes"):
                        data = b"".join(file_content.iter_bytes())
                    elif hasattr(file_content, "read"):
                        data = file_content.read()
                    else:
                        data = bytes(file_content)

                    logger.info("Downloaded file %s from Claude API (%d bytes)", file_id, len(data))

                    # Store in local cache for future requests
                    from core.file_store import store_file
                    store_file(
                        data=data,
                        filename=dl_filename,
                        tool_name="claude_files_api",
                        file_id=file_id,
                    )

                    return Response(
                        content=data,
                        media_type=mime,
                        headers={
                            "Content-Disposition": f'attachment; filename="{dl_filename}"',
                            "Content-Length": str(len(data)),
                        },
                    )
                except anthropic.NotFoundError:
                    logger.warning("File %s not found in Claude API", file_id)
                except Exception as e:
                    logger.error("Claude Files API download failed: %s", e)

        except ImportError:
            logger.warning("anthropic package not available for Files API fallback")
        except Exception as e:
            logger.error("Files API fallback error: %s", e)

    raise HTTPException(status_code=404, detail=f"File {file_id} not found")


@router.get("/{file_id}/info")
async def file_info(file_id: str):
    """Get file metadata without downloading."""
    entry = get_file(file_id)
    if entry is None:
        return JSONResponse(
            content={"file_id": file_id, "exists": False},
            status_code=404,
        )
    return {
        "file_id":   entry.file_id,
        "filename":  entry.filename,
        "file_type": entry.file_type,
        "size_kb":   entry.size_kb,
        "exists":    True,
    }


@router.get("/generated")
async def list_generated_files():
    """List all currently available generated files."""
    return {"files": list_files()}
